### ISSUE TITLE
Change license to GPL

### ISSUE THREAD

**Issue by mcustiel** [dxw/codeception-notify-module#1]
Hi. I am the original developer of phiremock-codeception-extension.
I am glad you found my service useful and you decided to extend it, and I thank you for that. But I would have to ask you to please change the license of your extension to GPL, since it is the version I used for phiremock-codeception-extension and it forces extensions to be released in the same way. MIT license would allow people to extend it and not make the result public and free, and that's not something I would like.
Thank you.
Best,
Mariano

**Comment by Floppy** [comment]
Thanks for raising this @mcustiel. After checking the FAQs and interpretations of the GPL to clarify, we agree that it should be GPL'd, not MIT, as it can't function without your code being in place as a dependency. That was an oversight in the original creation of the extension; sorry about that!

We'll make that change shortly and close this issue when it's done.

For future reference, the specific FAQs we base that on are https://www.gnu.org/licenses/gpl-faq.html#GPLModuleLicense and https://www.gnu.org/licenses/gpl-faq.html#IfInterpreterIsGPL. 

Also, we don't think that licensing this as GPL would require GPLing code that uses it purely during testing and development.

**Comment by mcustiel** [comment]
Thank you @Floppy ! I agree, when used as a testing tool the code using it doesn't need to have GPL license.
